#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.zshrc
ln -s $DOTFILES/zsh/zshrc $HOME/.zshrc

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

mkdir -p $HOME/.local/bin

rm -rf $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.config/phpactor
ln -s $DOTFILES/phpactor $HOME/.config/phpactor

rm -rf $HOME/.config/i3
ln -s $DOTFILES/i3 $HOME/.config/i3

rm -rf $HOME/.config/picom
ln -s $DOTFILES/picom $HOME/.config/picom

rm -rf $HOME/.config/polybar
ln -s $DOTFILES/polybar $HOME/.config/polybar

rm -rf $HOME/.config/polybar-weather
ln -s $DOTFILES/polybar-weather $HOME/.config/polybar-weather

rm -rf $HOME/.config/dunst
ln -s $DOTFILES/dunst $HOME/.config/dunst

rm -rf $HOME/.config/rofi
ln -s $DOTFILES/rofi $HOME/.config/rofi

mkdir -p $HOME/.local/share/fonts
cp $DOTFILES/fonts/nonicons.ttf $HOME/.local/share/fonts

rm -rf $HOME/scripts
cp -r $DOTFILES/scripts $HOME/scripts


echo "==============="
echo "==== DONE ====="
echo "==============="
